### ISSUE TITLE
Mailchimp Plugin Sync Job Not Running Correctly

### ISSUE THREAD

**Issue by jaredbrandon** [BEMADEV/Rock#125]
The Mailchimp Sync plugin is not running as described in the documentation. It also takes hours to complete, which does not seem correct. I need it to run faster and more frequently so that I know my lists are updated whenever I need to send an email.

**Expected behavior:**

Sync job runs every 20 minutes as stated in the documentation. 

**Actual behavior:**

Out of the box, Sync job is set to run daily at 1:00 AM but doesn't run unless I start it manually. Last successful run was on 9/21/20 at 1:20 PM when I manually ran it. It took 3 hrs 44 minutes to run, which I don't think is normal. Previously, it took 2.5 hours. I do not get an error message, and the data does seem to sync between Rock and MailChimp. But it should be happening more frequently, and faster.

### Versions

* **Rock Version:** [Rock McKinley 11.1 (1.11.1.1)]
* **Client Culture Setting:** [en-US}

**Comment by tcavaletto** [comment]
@jarednbrandon We've pushed a newer version of the plugin that allows the user to specify how many days back to sync updates for. This will drastically increase the time it takes to load the plugin for you. Due to how the plugin works ( it uses a new data point to check for last updated date time) there won't be a change in the job load time until N+1 days after you install, with N being the number of days you configure.

Currently we have the job set to run daily due to the length of time it takes to run it. I've updated the documentation to reflect this. Once you see faster load times, you can replace the job's cron expression with the one below to set it to run every 20 minutes:
0 0/20 * 1/1 * ? *

Please let us know if you continue having issues after installing the update.

**Comment by jaredbrandon** [comment]
That all makes sense, thanks for the quick reply!
